version: "3.9"

services:
  api:
    build: ./Backend
    container_name: cigarreria_api
    restart: always
    env_file:
      - ./Backend/.env
    ports:
      - "8000:8000"
    depends_on:
      - mysql
      - redis

  mysql:
    image: mysql:8.0
    container_name: cigarreria_mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${Pass_Sql}
      MYSQL_DATABASE: ${Database_Sql}
    ports:
      - "3307:3306"
    volumes:
      - "C:/BaseDatos/cigarreria:/var/lib/mysql"

  redis:
    image: redis:7
    container_name: cigarreria_redis
    restart: always
    ports:
      - "6379:6379"

  frontend:
    build: ./Frontend
    container_name: cigarreria_frontend
    ports:
      - "5173:80"
    depends_on:
      - api